sudo: required
services:
  - docker

before_install:
  - docker build -t leondo/vitest -f Dockerfile.dev .

script:
  - docker run leondo/vitest yarn run test --run --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-123456789"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"